from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, List, Optional


def build_simple_html(
    title: str,
    subtitle: str,
    facility_name: str,
    now_str: Optional[str] = None,
    notes: Optional[List[str]] = None,
) -> str:
    now_str = now_str or datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    notes = notes or []

    items = "".join(f"<li>{n}</li>" for n in notes)
    notes_html = f"<ul>{items}</ul>" if items else ""

    # Simple, mobile-friendly HTML (no external assets)
    return f"""
    <!doctype html>
    <html>
    <head>
      <meta charset='utf-8'/>
      <meta name='viewport' content='width=device-width, initial-scale=1'/>
      <style>
        body{{font-family:Arial,Helvetica,sans-serif;font-size:12px;color:#111;margin:0;padding:0;background:#f6f7f9;}}
        .wrap{{max-width:820px;margin:0 auto;padding:18px;}}
        .card{{background:#fff;border:1px solid #e5e7eb;border-radius:10px;padding:16px;}}
        h1{{font-size:18px;margin:0 0 6px 0;}}
        h2{{font-size:13px;margin:0 0 12px 0;color:#374151;font-weight:normal;}}
        .meta{{font-size:12px;color:#6b7280;margin-top:10px;}}
        .footer{{font-size:11px;color:#6b7280;margin-top:14px;border-top:1px solid #eee;padding-top:10px;}}
      </style>
    </head>
    <body>
      <div class='wrap'>
        <div class='card'>
          <h1>{title}</h1>
          <h2>{subtitle}</h2>
          <div><b>Facility:</b> {facility_name}</div>
          <div class='meta'><b>Generated:</b> {now_str}</div>
          {notes_html}
          <div class='footer'>
            Data Source: Selec MFM384 meters | Generated by MFM384 Monitoring
          </div>
        </div>
      </div>
    </body>
    </html>
    """


def build_params_table(snapshot: Dict[str, Any], keys: List[str], title: str = "Current Parameters") -> str:
    """Return an inline HTML table for a small set of snapshot values."""
    def _fmt(x: Any) -> str:
        if x is None:
            return "N/A"
        s = str(x).strip()
        if not s or s in ("—", "-", "N/A"):
            return "N/A"
        return s

    body_rows = "".join(
        f"<tr><td style='padding:6px 8px;border:1px solid #e5e7eb;background:#f9fafb;'><b>{k}</b></td>"
        f"<td style='padding:6px 8px;border:1px solid #e5e7eb;'>{_fmt(snapshot.get(k))}</td></tr>"
        for k in keys
    )

    return (
        f"<h3 style='margin:14px 0 6px 0;font-size:13px;color:#111;'>{title}</h3>"
        "<table style='width:100%;border-collapse:collapse;font-size:12px;'>"
        f"{body_rows}"
        "</table>"
    )
