"""
SQLite Historian for SCADA Power Monitor
=========================================
Stores aggregated meter readings in a single SQLite database file.

This replaces the flat-file CSV approach with a proper relational store
that supports fast time-range queries, smaller disk footprint, and clean
retention management.

Design
------
• One .db file per base folder.  Default: <logs_dir>/historian.db
• WAL journal mode   — allows read queries while writes are in-flight.
• synchronous=NORMAL — fast enough for SCADA rates; safe under WAL.
• Writer thread owns one persistent connection (thread-local singleton).
• Read queries always open a short-lived read-only URI connection so
  they never block the writer thread.
• Values stored as a compact JSON blob — no schema migration needed
  when the operator adds or removes logged parameters.

Table: log_rows
---------------
    id             INTEGER PK   — row identity
    ts_epoch       REAL         — Unix epoch wall clock (index for fast range queries)
    monotonic_ts   REAL         — time.monotonic() at sample time; 0 if unavailable
                                   Used to detect clock jumps in post-analysis.
    ts             TEXT         — "YYYY-MM-DD HH:MM:SS" (human-readable)
    source         TEXT         — "TOTAL" | "M1" | "M2" …
    interval_s     INTEGER      — logging interval [s]
    mode           TEXT         — "instant" | "min" | "avg" | "max"
    data_valid     INTEGER      — 1 = all samples valid, 0 = comm error
    sample_ct      INTEGER      — aggregation sample count
    quality        TEXT         — "GOOD" | "STALE" | "COMM_LOST"
    quality_flags  TEXT         — comma-separated flag tags, e.g. "clock_jump,ct_pt_warn"
                                   Empty string means no flags.  Defined flags:
                                     clock_jump  — wall/monotonic divergence ≥ warn threshold
                                     rollover    — energy accumulator rollover detected
                                     ct_pt_warn  — CT/PT-scaled value outside expected range
    serial_no      TEXT         — meter serial number (or "TOTAL")
    values_json    TEXT         — JSON: {"kW": 12.34, "kVA": 13.5, …}
    tier           INTEGER      — 0 = full-resolution (hot), 1 = downsampled (warm)
                                   Default 0.  Warm rows are generated by retention
                                   downsampling and replace N hot rows with one hourly avg.
"""
from __future__ import annotations

import json
import math
import os
import sqlite3
import threading
from datetime import datetime, timedelta
from typing import Any, Dict, List, Optional, Tuple

from utils.logger import setup_logger

logger = setup_logger("historian")

_CREATE_TABLE = """
CREATE TABLE IF NOT EXISTS log_rows (
    id             INTEGER PRIMARY KEY AUTOINCREMENT,
    ts_epoch       REAL    NOT NULL,
    monotonic_ts   REAL    NOT NULL DEFAULT 0.0,
    ts             TEXT    NOT NULL,
    source         TEXT    NOT NULL,
    interval_s     INTEGER NOT NULL,
    mode           TEXT    NOT NULL,
    data_valid     INTEGER NOT NULL DEFAULT 1,
    sample_ct      INTEGER NOT NULL DEFAULT 0,
    quality        TEXT    NOT NULL DEFAULT 'GOOD',
    quality_flags  TEXT    NOT NULL DEFAULT '',
    serial_no      TEXT    NOT NULL DEFAULT '',
    values_json    TEXT    NOT NULL DEFAULT '{}',
    tier           INTEGER NOT NULL DEFAULT 0
)
"""
_CREATE_IDX_EPOCH        = "CREATE INDEX IF NOT EXISTS idx_epoch        ON log_rows(ts_epoch)"
_CREATE_IDX_SOURCE_EPOCH = "CREATE INDEX IF NOT EXISTS idx_source_epoch ON log_rows(source, ts_epoch)"
_CREATE_IDX_TIER         = "CREATE INDEX IF NOT EXISTS idx_tier         ON log_rows(tier, ts_epoch)"

# Migration: add new columns to pre-existing databases that only have the original schema.
# ALTER TABLE ADD COLUMN is safe and idempotent — SQLite ignores it if the column exists.
_MIGRATE_STMTS = [
    "ALTER TABLE log_rows ADD COLUMN monotonic_ts  REAL    NOT NULL DEFAULT 0.0",
    "ALTER TABLE log_rows ADD COLUMN quality_flags TEXT    NOT NULL DEFAULT ''",
    "ALTER TABLE log_rows ADD COLUMN tier          INTEGER NOT NULL DEFAULT 0",
]

_INSERT = """
INSERT INTO log_rows
    (ts_epoch, monotonic_ts, ts, source, interval_s, mode, data_valid, sample_ct,
     quality, quality_flags, serial_no, values_json, tier)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
"""

# Downsampling INSERT for warm-tier rows produced by retention management.
_INSERT_WARM = """
INSERT INTO log_rows
    (ts_epoch, monotonic_ts, ts, source, interval_s, mode, data_valid, sample_ct,
     quality, quality_flags, serial_no, values_json, tier)
VALUES (?, 0.0, ?, ?, ?, 'avg', ?, ?, 'GOOD', '', ?, ?, 1)
"""


class Historian:
    """
    Thread-safe SQLite historian.

    The *writer thread* calls :meth:`write_row` — it owns a single persistent
    connection created on first use.  All other threads (UI, export) should
    use :meth:`query_range` / :meth:`get_sources` / :meth:`get_date_range`
    which open their own short-lived read-only connections.
    """

    def __init__(self, db_path: str) -> None:
        self.db_path = db_path
        # Per-thread write connection (only used by the writer thread)
        self._local = threading.local()
        # Initialise schema (safe to call from any thread — uses own conn)
        self._init_schema()

    # ── Schema ────────────────────────────────────────────────────────────────

    def _init_schema(self) -> None:
        """Create tables and indexes if they do not yet exist.

        Also runs non-destructive column migrations so existing databases gain
        the new monotonic_ts / quality_flags / tier columns transparently.
        """
        try:
            os.makedirs(os.path.dirname(self.db_path) or ".", exist_ok=True)
        except OSError:
            pass
        conn = sqlite3.connect(self.db_path, timeout=10)
        try:
            conn.execute("PRAGMA busy_timeout=10000")
            conn.execute("PRAGMA journal_mode=WAL")
            conn.execute("PRAGMA synchronous=NORMAL")
            conn.execute(_CREATE_TABLE)
            conn.execute(_CREATE_IDX_EPOCH)
            conn.execute(_CREATE_IDX_SOURCE_EPOCH)
            conn.execute(_CREATE_IDX_TIER)
            # Non-destructive migrations: add columns silently if they don't exist.
            for stmt in _MIGRATE_STMTS:
                try:
                    conn.execute(stmt)
                except Exception:
                    pass  # column already exists — safe to ignore
            conn.commit()
        finally:
            conn.close()

    # ── Writer thread API ─────────────────────────────────────────────────────

    def _write_conn(self) -> sqlite3.Connection:
        """Return (or lazily create) the per-thread write connection."""
        conn = getattr(self._local, "conn", None)
        if conn is None:
            conn = sqlite3.connect(self.db_path, timeout=10, check_same_thread=False)
            conn.execute("PRAGMA busy_timeout=10000")
            conn.execute("PRAGMA journal_mode=WAL")
            conn.execute("PRAGMA synchronous=NORMAL")
            # Batch inserts are flushed every N ms; reduces fsync overhead.
            conn.execute("PRAGMA wal_autocheckpoint=200")
            self._local.conn = conn
        return conn

    def write_row(
        self,
        ts: str,
        ts_epoch: float,
        source: str,
        interval_s: int,
        mode: str,
        data_valid: bool,
        sample_ct: int,
        quality: str,
        serial_no: str,
        values: Dict[str, Any],
        monotonic_ts: float = 0.0,
        quality_flags: str = "",
    ) -> None:
        """
        Persist one aggregated row.

        Must be called from the *writer thread* only.
        Values dict keys with non-finite floats are silently dropped.

        Parameters
        ----------
        monotonic_ts : float
            time.monotonic() recorded at sample time.  Used for post-analysis
            clock-jump detection.  Pass 0.0 if unavailable (e.g. restored rows).
        quality_flags : str
            Comma-separated flag tags.  See module docstring for defined flags.
            Example: "clock_jump,ct_pt_warn"
        """
        # Sanitise values — drop non-finite to keep JSON clean
        clean: Dict[str, float] = {}
        for k, v in (values or {}).items():
            try:
                f = float(v)
                if math.isfinite(f):
                    clean[k] = round(f, 6)
            except (TypeError, ValueError):
                pass

        conn = self._write_conn()
        conn.execute(_INSERT, (
            float(ts_epoch),
            float(monotonic_ts or 0.0),
            ts,
            source,
            int(interval_s),
            str(mode),
            1 if data_valid else 0,
            int(sample_ct),
            str(quality),
            str(quality_flags or ""),
            str(serial_no or ""),
            json.dumps(clean, separators=(",", ":")),
            0,  # tier 0 = hot (full-resolution)
        ))
        conn.commit()

    # ── Read API (any thread) ─────────────────────────────────────────────────

    def _read_conn(self) -> sqlite3.Connection:
        """Open a read-only connection.  Caller must close it."""
        try:
            # URI mode read-only prevents accidental writes
            conn = sqlite3.connect(
                f"file:{self.db_path}?mode=ro",
                uri=True,
                timeout=10,
                check_same_thread=False,
            )
        except Exception:
            # Fallback for older SQLite or Windows path quirks
            conn = sqlite3.connect(self.db_path, timeout=10, check_same_thread=False)
        try:
            conn.execute("PRAGMA busy_timeout=10000")
        except Exception:
            pass
        conn.row_factory = sqlite3.Row
        return conn

    def query_range(
        self,
        from_epoch: float,
        to_epoch: float,
        sources: Optional[List[str]] = None,
    ) -> List[Dict[str, Any]]:
        """
        Return rows in [from_epoch, to_epoch], optionally filtered by source.

        Returns a list of dicts with keys:
            ts, ts_epoch, source, interval_s, mode, data_valid,
            sample_ct, quality, serial_no, values (dict)
        """
        conn = self._read_conn()
        try:
            if sources:
                ph = ",".join("?" * len(sources))
                cur = conn.execute(
                    f"SELECT ts,ts_epoch,monotonic_ts,source,interval_s,mode,data_valid,"
                    f"sample_ct,quality,quality_flags,serial_no,values_json,tier "
                    f"FROM log_rows "
                    f"WHERE ts_epoch>=? AND ts_epoch<=? AND source IN ({ph}) "
                    f"ORDER BY ts_epoch,source",
                    [from_epoch, to_epoch, *sources],
                )
            else:
                cur = conn.execute(
                    "SELECT ts,ts_epoch,monotonic_ts,source,interval_s,mode,data_valid,"
                    "sample_ct,quality,quality_flags,serial_no,values_json,tier "
                    "FROM log_rows "
                    "WHERE ts_epoch>=? AND ts_epoch<=? "
                    "ORDER BY ts_epoch,source",
                    (from_epoch, to_epoch),
                )
            rows = []
            for r in cur:
                d = dict(r)
                try:
                    d["values"] = json.loads(d.pop("values_json") or "{}")
                except Exception:
                    d["values"] = {}
                rows.append(d)
            return rows
        except Exception as exc:
            logger.warning("Historian.query_range failed: %s", exc)
            return []
        finally:
            conn.close()

    def query_recent(
        self,
        sources: Optional[List[str]] = None,
        limit: int = 100,
    ) -> List[Dict[str, Any]]:
        """
        Return the *limit* most-recent hot-tier rows, newest first.

        Used by the REST /api/v1/history endpoint so remote clients can pull
        sparkline / trend data without a time-range query.

        Each row dict: {ts, ts_epoch, source, interval_s, values (dict),
                        quality, quality_flags, tier}
        """
        conn = self._read_conn()
        try:
            if sources:
                ph = ",".join("?" * len(sources))
                cur = conn.execute(
                    f"SELECT ts,ts_epoch,source,interval_s,quality,quality_flags,"
                    f"values_json,tier "
                    f"FROM log_rows "
                    f"WHERE tier=0 AND source IN ({ph}) "
                    f"ORDER BY ts_epoch DESC LIMIT ?",
                    [*sources, int(limit)],
                )
            else:
                cur = conn.execute(
                    "SELECT ts,ts_epoch,source,interval_s,quality,quality_flags,"
                    "values_json,tier "
                    "FROM log_rows "
                    "WHERE tier=0 "
                    "ORDER BY ts_epoch DESC LIMIT ?",
                    (int(limit),),
                )
            rows = []
            for r in cur:
                d = dict(r)
                try:
                    d["values"] = json.loads(d.pop("values_json") or "{}")
                except Exception:
                    d["values"] = {}
                rows.append(d)
            return rows
        except Exception as exc:
            logger.warning("Historian.query_recent failed: %s", exc)
            return []
        finally:
            conn.close()

    def get_sources(self) -> List[str]:
        """Return list of distinct source names (alphabetical)."""
        conn = self._read_conn()
        try:
            cur = conn.execute(
                "SELECT DISTINCT source FROM log_rows ORDER BY source"
            )
            return [r[0] for r in cur]
        except Exception:
            return []
        finally:
            conn.close()

    def get_date_range(self) -> Tuple[str, str]:
        """
        Return (earliest_ts, latest_ts) as 'YYYY-MM-DD HH:MM:SS' strings.
        Returns ('', '') if the database is empty.
        """
        conn = self._read_conn()
        try:
            cur = conn.execute("SELECT MIN(ts), MAX(ts) FROM log_rows")
            row = cur.fetchone()
            if row and row[0]:
                return (row[0], row[1])
            return ("", "")
        except Exception:
            return ("", "")
        finally:
            conn.close()

    def row_count(self) -> int:
        """Return total number of rows in the database."""
        conn = self._read_conn()
        try:
            cur = conn.execute("SELECT COUNT(*) FROM log_rows")
            row = cur.fetchone()
            return int(row[0]) if row else 0
        except Exception:
            return 0
        finally:
            conn.close()

    # ── Maintenance ───────────────────────────────────────────────────────────

    def purge_before(self, cutoff_epoch: float) -> int:
        """
        Delete all rows with ts_epoch < cutoff_epoch (tier 0 hot rows only).

        Called from the writer thread (uses _write_conn).
        Returns the number of rows deleted.
        Runs VACUUM when > 1000 rows are deleted to reclaim disk space.
        """
        conn = self._write_conn()
        try:
            # Only purge tier-0 (hot) rows; warm rows have their own cutoff.
            cur = conn.execute(
                "DELETE FROM log_rows WHERE ts_epoch < ? AND tier = 0",
                (cutoff_epoch,),
            )
            conn.commit()
            n = cur.rowcount
            if n > 1000:
                try:
                    conn.execute("VACUUM")
                    conn.commit()
                except Exception:
                    pass
            return n
        except Exception as exc:
            logger.warning("Historian.purge_before failed: %s", exc)
            return 0

    def downsample_to_warm(
        self,
        hot_older_than: float,
        warm_interval_s: int = 3600,
        sources: Optional[List[str]] = None,
    ) -> Tuple[int, int]:
        """
        Downsample hot-tier rows older than *hot_older_than* (epoch) into
        hourly-average warm-tier rows, then delete the originals.

        Only processes tier-0 rows.  Does nothing if there is nothing to compress.
        Called from the writer thread (uses _write_conn).

        Parameters
        ----------
        hot_older_than : float
            Epoch cutoff.  Hot rows with ts_epoch < this value are compressed.
        warm_interval_s : int
            Bucket width for averaging, default 3600 (1 hour).
        sources : list[str] or None
            Restrict to these sources; None = all.

        Returns
        -------
        (warm_rows_written, hot_rows_deleted) : tuple[int, int]
        """
        conn = self._write_conn()
        try:
            # Determine source list
            if sources:
                src_list = sources
            else:
                cur = conn.execute(
                    "SELECT DISTINCT source FROM log_rows WHERE ts_epoch < ? AND tier=0",
                    (hot_older_than,),
                )
                src_list = [r[0] for r in cur.fetchall()]

            warm_written = 0
            hot_deleted = 0

            for src in src_list:
                # Read hot rows for this source in the compression window
                cur = conn.execute(
                    "SELECT id, ts_epoch, serial_no, interval_s, data_valid, "
                    "sample_ct, values_json "
                    "FROM log_rows "
                    "WHERE source=? AND ts_epoch<? AND tier=0 "
                    "ORDER BY ts_epoch",
                    (src, hot_older_than),
                )
                hot_rows = cur.fetchall()
                if not hot_rows:
                    continue

                # Group by warm bucket (floor to warm_interval_s)
                buckets: Dict[int, List[Any]] = {}
                for row in hot_rows:
                    bucket = int(row[1]) // warm_interval_s * warm_interval_s
                    buckets.setdefault(bucket, []).append(row)

                ids_to_delete: List[int] = []
                for bucket_ts, rows in sorted(buckets.items()):
                    ids_to_delete.extend(r[0] for r in rows)

                    # Average all numeric values across the bucket
                    accum: Dict[str, List[float]] = {}
                    total_valid = 0
                    total_samples = 0
                    serial = rows[0][2] if rows else ""
                    for r in rows:
                        if r[4]:  # data_valid
                            total_valid += 1
                        total_samples += int(r[5] or 0)
                        try:
                            vals = json.loads(r[6] or "{}")
                        except Exception:
                            vals = {}
                        for k, v in vals.items():
                            try:
                                accum.setdefault(k, []).append(float(v))
                            except (TypeError, ValueError):
                                pass

                    avg_vals: Dict[str, float] = {
                        k: round(sum(v_list) / len(v_list), 6)
                        for k, v_list in accum.items()
                        if v_list
                    }
                    bucket_ts_str = datetime.fromtimestamp(bucket_ts).strftime("%Y-%m-%d %H:%M:%S")
                    data_valid_flag = 1 if total_valid >= (len(rows) // 2 + 1) else 0

                    conn.execute(
                        _INSERT_WARM,
                        (
                            float(bucket_ts),
                            bucket_ts_str,
                            src,
                            warm_interval_s,
                            data_valid_flag,
                            total_samples,
                            str(serial or ""),
                            json.dumps(avg_vals, separators=(",", ":")),
                        ),
                    )
                    warm_written += 1

                # Delete the original hot rows in one statement
                if ids_to_delete:
                    ph = ",".join("?" * len(ids_to_delete))
                    conn.execute(f"DELETE FROM log_rows WHERE id IN ({ph})", ids_to_delete)
                    hot_deleted += len(ids_to_delete)

            conn.commit()
            return warm_written, hot_deleted

        except Exception as exc:
            logger.warning("Historian.downsample_to_warm failed: %s", exc)
            try:
                conn.rollback()
            except Exception:
                pass
            return 0, 0

    def purge_warm_before(self, cutoff_epoch: float) -> int:
        """Delete warm-tier rows older than cutoff_epoch. Returns rows deleted."""
        conn = self._write_conn()
        try:
            cur = conn.execute(
                "DELETE FROM log_rows WHERE ts_epoch < ? AND tier = 1",
                (cutoff_epoch,),
            )
            conn.commit()
            return cur.rowcount
        except Exception as exc:
            logger.warning("Historian.purge_warm_before failed: %s", exc)
            return 0

    def db_size_mb(self) -> float:
        """Current .db file size in megabytes."""
        try:
            return os.path.getsize(self.db_path) / (1024 * 1024)
        except OSError:
            return 0.0

    # ── Lifecycle ─────────────────────────────────────────────────────────────

    def close(self) -> None:
        """Close the per-thread write connection if open."""
        conn = getattr(self._local, "conn", None)
        if conn is not None:
            try:
                conn.close()
            except Exception:
                pass
            self._local.conn = None

    # ── Convenience ───────────────────────────────────────────────────────────

    @staticmethod
    def epoch_for_date(date_str: str, end_of_day: bool = False) -> float:
        """Convert 'YYYY-MM-DD' to Unix epoch (start or end of day)."""
        fmt = "%Y-%m-%d"
        dt = datetime.strptime(date_str, fmt)
        if end_of_day:
            dt = dt.replace(hour=23, minute=59, second=59)
        return dt.timestamp()

    def rows_to_csv_lines(
        self,
        rows: List[Dict[str, Any]],
        source: str,
    ) -> Tuple[List[str], List[Dict]]:
        """
        Convert a list of historian rows for one source into CSV-ready
        column headers and row dicts.

        Returns (header_list, row_dicts) suitable for csv.DictWriter.
        """
        if not rows:
            return (
                ["Timestamp", "Source", "SerialNo", "IntervalSec",
                 "Mode", "DataValid", "SampleCount", "Quality"],
                [],
            )
        # Collect all parameter keys in insertion order
        all_keys: List[str] = []
        seen: set = set()
        for r in rows:
            for k in (r.get("values") or {}):
                if k not in seen:
                    all_keys.append(k)
                    seen.add(k)

        meta_cols = ["Timestamp", "Source", "SerialNo", "IntervalSec",
                     "Mode", "DataValid", "SampleCount", "Quality"]
        headers = meta_cols + all_keys

        out_rows = []
        for r in rows:
            if r.get("source") != source:
                continue
            vals = r.get("values") or {}
            d: Dict[str, Any] = {
                "Timestamp":   r["ts"],
                "Source":      r["source"],
                "SerialNo":    r.get("serial_no", ""),
                "IntervalSec": r.get("interval_s", ""),
                "Mode":        r.get("mode", ""),
                "DataValid":   r.get("data_valid", 1),
                "SampleCount": r.get("sample_ct", 0),
                "Quality":     r.get("quality", ""),
            }
            for k in all_keys:
                v = vals.get(k)
                d[k] = f"{v:.4f}" if isinstance(v, float) else (v or "")
            out_rows.append(d)
        return headers, out_rows
